export { Home } from './Home'
export { QuienesSomos } from './QuienesSomos'
export { Blog } from './Blog'
export { Contacto} from './Contacto'
export { Noticia1 } from './Noticias'
export { Noticia2 } from './Noticias2'
export { Noticia3 } from './Noticias3'
export { Noticia4 } from './Noticias4'